version: 2.1

jobs:
  static:
    docker:
      - image: cinexpert/alpine-php8-build:latest
        auth:
          username: ${DOCKER_HUB_LOGIN}
          password: ${DOCKER_HUB_PASSWORD}
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: Composer install
          command: |
            ./composer.phar update -n
      - run:
          name: PHPStan
          command: |
            mkdir -p results/PHPStan
            php -d memory_limit=4G vendor/bin/phpstan analyze --error-format=junit > results/PHPStan/result.xml; php -d memory_limit=4G vendor/bin/phpstan analyze
      - run:
          name: PHPCS
          command: |
            mkdir -p results/PHPCS
            vendor/bin/phpcs src
      - store_test_results:
          path: results
      - store_artifacts:
          path: results

workflows:
  version: 2
  build:
    jobs:
      - static
